version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    resource_class: large
    parallelism: 5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install --force
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build library
          command: npm run release
      - run:
          name: Run unit tests
          command: npm run test --shard=$(expr $CIRCLE_NODE_INDEX + 1)/$CIRCLE_NODE_TOTAL
      - run:
          name: Run e2e tests
          command: npm run test:e2e --shard=$(expr $CIRCLE_NODE_INDEX + 1)/$CIRCLE_NODE_TOTAL
      - run:
         name: Submit to Codecov
         command: npm run codecov
